name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  api:
    name: API Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter (if available)
        run: npm run lint || echo "No lint script found"
        continue-on-error: true
      
      - name: Run tests
        run: npm run selftest || npm test || echo "No test script found"
        continue-on-error: true

  jobs:
    name: Background Jobs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jobs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: jobs/package-lock.json
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Run job tests
        run: npm run selftest || npm test || echo "No test script found"
        continue-on-error: true

  web:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Run type check
        run: npm run type-check || npx tsc --noEmit || echo "No type check available"
        continue-on-error: true
      
      - name: Build project
        run: npm run build

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Security audit - API
        working-directory: ./api
        run: npm audit --audit-level=moderate || echo "Security audit completed with warnings"
        continue-on-error: true
      
      - name: Security audit - Jobs
        working-directory: ./jobs
        run: npm audit --audit-level=moderate || echo "Security audit completed with warnings"
        continue-on-error: true
      
      - name: Security audit - Web
        working-directory: ./web
        run: npm audit --audit-level=moderate || echo "Security audit completed with warnings"
        continue-on-error: true
